#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + "/../lib")
require 'coupler'

logger = Logger.new(File.dirname(__FILE__) + "/../log/runner.log")
logger.level = Logger::DEBUG
Coupler.logger = logger 

options = Coupler::Options.parse(ARGV)
Coupler::Runner.run(options)
