#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + "/../lib")
require 'coupler'

#options        = Coupler::Options.parse(ARGV)
#logger         = Logger.new(options.log_file)
#logger.level   = options.log_level
#Coupler.logger = logger 

Coupler.runner.run
