#!/usr/bin/env ruby
require 'rubygems'
require 'spec'

args = ["-O", File.expand_path(File.dirname(__FILE__) + "/../spec/spec.opts")] + ARGV

# run the last touched file if no arguments
if ARGV.empty?
  spec_files = Dir[File.expand_path(File.dirname(__FILE__) + "/../spec") + "/**/*_spec.rb"]
  spec_files.sort! {|a, b| File.mtime(b) <=> File.mtime(a) }
  args << spec_files[0]

  puts "Running #{spec_files[0]}"
end

exit ::Spec::Runner::CommandLine.run(::Spec::Runner::OptionParser.parse(args, STDERR, STDOUT))
